export enum StatusCasoEnum {
  AGUARDANDO_NOTIFICACOES = 'AGUARDANDO_NOTIFICACOES',
  EM_PREPARACAO = 'EM_PREPARACAO',
  EM_PLANEJAMENTO = 'EM_PLANEJAMENTO',
  EM_INVESTIGACAO = 'EM_INVESTIGACAO',
  EM_INTERVENCAO = 'EM_INTERVENCAO',
  INTERVENCAO_FINALIZADA = 'INTERVENCAO_FINALIZADA',
}
