services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: zerobito
    ports:
      - '5432:5432'
    networks:
      - zerobito-network
  redis:
    image: redis:latest 
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - zerobito-network

networks:
  zerobito-network:
    driver: bridge

volumes:
  my_dbdata:
