export enum StatusConclusaoAcaoIntervencaoEnum {
    CONCLUIDA_EXITO = 'CONCLUIDA_EXITO',
    CONCLUIDA_SATISFATORIA = 'CONCLUIDA_SATISFATORIA',
    CONCLUIDA_PARCIAL = 'CONCLUIDA_PARCIAL',
    NAO_CONCLUIDA = 'NAO_CONCLUIDA'
}
