name: Build e Deploy Docker Backend

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Build da imagem Docker
        run: |
          docker build -t zerobito-backend:latest .

      - name: Salvar imagem como tar
        run: |
          docker save zerobito-backend:latest -o zerobito-backend.tar

      - name: Enviar imagem para VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_VM }}
          port: ${{ secrets.SSH_PORT }}
          source: "zerobito-backend.tar"
          target: "/opt/apps/backend"

      - name: Deploy na VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_VM }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/apps/backend

            echo "Carregando nova imagem..."
            docker load < zerobito-backend.tar

            echo "Parando containers..."
            docker compose down

            echo "Subindo nova versão..."
            docker compose up -d

            echo "Removendo tar..."
            rm zerobito-backend.tar

            echo "Deploy finalizado!"
